resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/papicella/SpringBootSimpleRest
    branch: master
- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: apples-pivotal-org
    space: development

jobs:
- name: job-deploy-app
  serial: true
  plan:
  - {get: SpringBootSimpleRest, trigger: true}
  - task: build
    privileged: true
    file: SpringBootSimpleRest/ci/build.yml
  - put: resource-deploy-web-app
    params:
      manifest: SpringBootSimpleRest/manifest.yml
      path: built-project/demo.jar

